"""initial migrations

Revision ID: 00728e8558bd
Revises: 3e09fd766d63
Create Date: 2025-01-29 07:17:46.991788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00728e8558bd"
down_revision: Union[str, None] = "3e09fd766d63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("language_code", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("is_premium", sa.Boolean(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "last_login",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "last_login")
    op.drop_column("users", "is_premium")
    op.drop_column("users", "language_code")
    # ### end Alembic commands ###
