"""Add channels, downloads tables

Revision ID: 3ccf6dc42140
Revises: 4164babf3803
Create Date: 2025-01-31 20:17:50.057048

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ccf6dc42140"
down_revision: Union[str, None] = "4164babf3803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_channels_channel_name", table_name="channels")
    op.create_index(
        op.f("ix_channels_channel_name"), "channels", ["channel_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channels_channel_name"), table_name="channels")
    op.create_index(
        "ix_channels_channel_name", "channels", ["channel_name"], unique=True
    )
    # ### end Alembic commands ###
