"""Add channels, downloads tables

Revision ID: 4164babf3803
Revises: 1c3bcef740fd
Create Date: 2025-01-31 20:17:13.114354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4164babf3803"
down_revision: Union[str, None] = "1c3bcef740fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("downloads", sa.Column("type", sa.String(length=50), nullable=True))
    op.add_column("downloads", sa.Column("format", sa.String(length=50), nullable=True))
    op.drop_column("downloads", "is_video")
    op.drop_column("downloads", "file_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "downloads",
        sa.Column(
            "file_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "downloads",
        sa.Column("is_video", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("downloads", "format")
    op.drop_column("downloads", "type")
    # ### end Alembic commands ###
