"""Add channels, downloads tables

Revision ID: 5c2bfff33307
Revises: 3ccf6dc42140
Create Date: 2025-01-31 20:17:53.189087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c2bfff33307"
down_revision: Union[str, None] = "3ccf6dc42140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
