"""initial migrations

Revision ID: e398cfc6322a
Revises: ce2f0df17998
Create Date: 2025-01-29 07:35:24.015812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e398cfc6322a"
down_revision: Union[str, None] = "ce2f0df17998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_name", sa.String(length=125), nullable=True),
        sa.Column("channel_link", sa.String(length=125), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channels_channel_link"), "channels", ["channel_link"], unique=False
    )
    op.create_index(
        op.f("ix_channels_channel_name"), "channels", ["channel_name"], unique=False
    )
    op.create_index(op.f("ix_channels_id"), "channels", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channels_id"), table_name="channels")
    op.drop_index(op.f("ix_channels_channel_name"), table_name="channels")
    op.drop_index(op.f("ix_channels_channel_link"), table_name="channels")
    op.drop_table("channels")
    # ### end Alembic commands ###
